#include "runtime.hpp"
#include "display.hpp"
namespace mayhem {
static Runtime runtime_instance{};
Runtime& runtime(){return runtime_instance;}
static constexpr ui::Color C_BG{7,11,8},C_PANEL{18,28,20},C_PANEL2{25,38,29},C_GRID{47,67,52},C_TEXT{208,220,210},C_MUTED{118,134,121},C_LIME{207,255,55},C_CYAN{0,220,220},C_GREEN{92,226,139},C_AMBER{255,179,78},C_RED{255,100,92};
static const char* tuner_name(uint32_t c){switch(c){case 1:return "R8XX";case 2:return "R828D";case 3:return "SYNTH";case 4:return "RECORD";default:return "UNKNOWN";}}
Runtime::Runtime(){host::display.attach(framebuffer_,width,height);}
void Runtime::set_receiver(uint32_t f,uint32_t r,int32_t l,uint32_t s){radio_.center_hz=f;radio_.sample_rate=r;radio_.level_tenths_dbfs=l;radio_.receiver_state=s;}
void Runtime::set_radio_details(int32_t g,uint32_t a,uint32_t d,uint32_t e,uint32_t t){radio_.gain_tenths_db=g;radio_.agc=a?1:0;radio_.dropped=d;radio_.errors=e;radio_.tuner_code=t;}
void Runtime::uint_text(int x,int y,uint32_t v,const ui::Style& style,int min_digits){char buf[16];int n=0;do{buf[n++]=(char)('0'+v%10);v/=10;}while(v&&n<15);while(n<min_digits&&n<15)buf[n++]='0';char out[16];int j=0;for(int i=n-1;i>=0;--i)out[j++]=buf[i];out[j]=0;painter_.draw_string({x,y},style,out);}
void Runtime::header(const char* title){ui::Style brand{C_PANEL,C_LIME},muted{C_PANEL,C_MUTED};painter_.fill_rectangle({0,0,240,24},C_PANEL);painter_.draw_string({6,4},brand,"MAYHEM",6);painter_.draw_string({112,4},muted,title,15);}
void Runtime::footer(){painter_.fill_rectangle({0,300,240,20},C_PANEL);const char* state="NO SOURCE";ui::Color c=C_MUTED;if(radio_.source_kind==2){state=radio_.receiver_state==2?"SIM ACTIVE":"SIM IDLE";c=C_AMBER;}else if(radio_.source_kind==3){state=radio_.receiver_state==2?"REPLAY":"REPLAY IDLE";c=C_AMBER;}else if(radio_.source_kind==1){state=radio_.receiver_state==2?"RX LIVE":radio_.receiver_state==1?"RX IDLE":"RADIO OFF";c=radio_.receiver_state==2?C_GREEN:radio_.receiver_state==1?C_AMBER:C_MUTED;}ui::Style s{C_PANEL,c};painter_.draw_string({6,302},s,state,11);ui::Style text{C_PANEL,C_TEXT};const uint32_t khz=radio_.center_hz/1000,mhz=khz/1000,frac=khz%1000;uint_text(112,302,mhz,text);painter_.draw_string({144,302},text,".",1);uint_text(152,302,frac,text,3);painter_.draw_string({184,302},{C_PANEL,C_MUTED},"MHz",3);}
void Runtime::status_line(){painter_.fill_rectangle({6,274,228,20},C_PANEL2);ui::Style m{C_PANEL2,C_MUTED},t{C_PANEL2,C_TEXT};painter_.draw_string({10,276},m,"RATE",4);uint_text(46,276,radio_.sample_rate/1000,t);painter_.draw_string({86,276},m,"k",1);painter_.draw_string({104,276},m,"DROP",4);uint_text(144,276,radio_.dropped,t);if(radio_.errors){painter_.draw_string({184,276},{C_PANEL2,C_RED},"ERR",3);uint_text(212,276,radio_.errors,{C_PANEL2,C_RED});}}
void Runtime::home(){header("HOME");painter_.draw_string({8,28},{C_BG,C_MUTED},"CATEGORY",8);static constexpr app::Category cats[]={app::Category::Receive,app::Category::Transmit,app::Category::Transceiver,app::Category::Utilities,app::Category::Games,app::Category::Settings};const auto& f=navigation_.top();for(uint32_t i=0;i<6;++i){int col=i%2,row=i/2;ui::Rect r{8+col*116,48+row*72,108,64};bool sel=i==f.selected;ui::Color bg=sel?C_PANEL2:C_PANEL;painter_.fill_rectangle(r,bg);painter_.draw_rectangle(r,sel?C_LIME:C_GRID);painter_.draw_string({r.left()+8,r.top()+10},{bg,sel?C_LIME:C_TEXT},app::category_name(cats[i]),12);uint32_t count=app::AppRegistry::instance().by_category_count(cats[i]);uint_text(r.left()+8,r.top()+34,count,{bg,count?C_CYAN:C_MUTED});painter_.draw_string({r.left()+28,r.top()+34},{bg,C_MUTED},count==1?"APP":"APPS",4);if(cats[i]==app::Category::Transmit)painter_.draw_string({r.left()+68,r.top()+34},{bg,C_RED},"LOCK",4);}}
void Runtime::category(){const auto& f=navigation_.top();header(app::category_name(f.category));painter_.draw_string({8,28},{C_BG,C_MUTED},"< BACK",6);const uint32_t count=app::AppRegistry::instance().by_category_count(f.category);if(!count){painter_.fill_rectangle({8,54,224,64},C_PANEL);painter_.draw_rectangle({8,54,224,64},C_GRID);painter_.draw_string({18,72},{C_PANEL,C_MUTED},"NO APPS",7);return;}const uint32_t maxv=7,offset=f.selected>=maxv?f.selected-maxv+1:0;for(uint32_t row=0;row<maxv&&offset+row<count;++row){uint32_t ord=offset+row,idx=app::AppRegistry::instance().by_category_index(f.category,ord);const app::AppEntry* a=app::AppRegistry::instance().at(idx);int y=52+(int)row*30;bool sel=ord==f.selected;ui::Color bg=sel?C_PANEL2:C_PANEL;painter_.fill_rectangle({8,y,224,26},bg);painter_.draw_rectangle({8,y,224,26},sel?C_LIME:C_GRID);painter_.draw_string({14,y+5},{bg,sel?C_LIME:C_TEXT},a?a->display_name:"?",20);const char* badge=(a&&a->flags&app::RequiresTx)?"LOCK":(a&&a->flags&app::Pending)?"PEND":"READY";ui::Color bc=(a&&a->flags&app::RequiresTx)?C_RED:(a&&a->flags&app::Pending)?C_AMBER:C_GREEN;painter_.draw_string({192,y+5},{bg,bc},badge,5);}}
void Runtime::application(){const auto& f=navigation_.top();const app::AppEntry* a=app::AppRegistry::instance().at(f.app_index);header(a?a->display_name:"APP");painter_.draw_string({8,28},{C_BG,C_MUTED},"< BACK",6);ui::Color border=(a&&a->flags&app::RequiresTx)?C_RED:(a&&a->flags&app::Pending)?C_AMBER:C_GREEN;painter_.fill_rectangle({8,52,224,202},C_PANEL);painter_.draw_rectangle({8,52,224,202},border);painter_.draw_string({18,64},{C_PANEL,C_MUTED},"NATIVE REGISTRY VIEW",20);painter_.draw_string({18,88},{C_PANEL,C_TEXT},a?a->display_name:"UNKNOWN",24);if(a&&a->flags&app::RequiresTx){painter_.draw_string({18,120},{C_PANEL,C_RED},"RECEIVE ONLY",12);painter_.draw_string({18,140},{C_PANEL,C_MUTED},"TRANSMIT UNAVAILABLE",20);}else if(a&&a->flags&app::Pending){painter_.draw_string({18,120},{C_PANEL,C_AMBER},"PORT PENDING",12);}else{painter_.draw_string({18,120},{C_PANEL,C_GREEN},"BROWSER PANEL ACTIVE",20);}painter_.draw_string({18,160},{C_PANEL,C_MUTED},"TUNER",5);painter_.draw_string({74,160},{C_PANEL,C_TEXT},tuner_name(radio_.tuner_code),8);painter_.draw_string({18,180},{C_PANEL,C_MUTED},"GAIN",4);if(radio_.agc)painter_.draw_string({74,180},{C_PANEL,C_TEXT},"AUTO",4);else{int32_t g=radio_.gain_tenths_db;if(g<0)g=-g;uint_text(74,180,(uint32_t)g/10,{C_PANEL,C_TEXT});painter_.draw_string({106,180},{C_PANEL,C_MUTED},"dB",2);}painter_.draw_string({18,200},{C_PANEL,C_MUTED},"DROPS",5);uint_text(74,200,radio_.dropped,{C_PANEL,C_TEXT});}
void Runtime::render(){host::display.clear(C_BG);const auto kind=navigation_.top().kind;if(kind==ScreenKind::Home)home();else if(kind==ScreenKind::Category)category();else application();status_line();footer();}
}
