import { cp, mkdir, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const web = path.join(root, "web");
const dist = path.join(root, "dist");

const registrySource = path.join(root, "src", "app_registry.json");
const registry = JSON.parse(await readFile(registrySource, "utf8"));
const categoryToCpp = Object.freeze({ Home: "CAT_HOME", Receive: "CAT_RECEIVE", Transmit: "CAT_TRANSMIT", Transceiver: "CAT_TRANSCEIVER", Utilities: "CAT_UTILITIES", Games: "CAT_GAMES", Settings: "CAT_SETTINGS", Debug: "CAT_DEBUG" });
function cppString(value) { return JSON.stringify(String(value)).replaceAll("\\u2028", "\\u2028").replaceAll("\\u2029", "\\u2029"); }
function coreFlags(entry) {
  const flags = [];
  if (["ready", "partial"].includes(entry.portState)) flags.push("APP_READY");
  if (entry.requiresReceive) flags.push("APP_RX");
  if (entry.requiresTransmit) flags.push("APP_TX");
  if (entry.portState === "browser port pending") flags.push("APP_PENDING");
  return flags.length ? flags.join("|") : "0";
}
const generatedJs = `// Generated by scripts/build.mjs from src/app_registry.json. Do not hand edit.\nexport const APPLICATION_DEFINITIONS = Object.freeze(${JSON.stringify(registry, null, 2)});\n`;
await writeFile(path.join(web, "src", "apps", "generated-registry.js"), generatedJs);
const generatedAppsDir = path.join(root, "src", "generated_apps");
await rm(generatedAppsDir, { recursive: true, force: true });
await mkdir(generatedAppsDir, { recursive: true });
const generatedAppSources = [];
for (let index = 0; index < registry.length; index += 1) {
  const entry = registry[index];
  const safeId = String(entry.id).replace(/[^a-zA-Z0-9_-]+/g, "-");
  const file = path.join(generatedAppsDir, `${String(index).padStart(2, "0")}-${safeId}.cpp`);
  const flags = [
    ["ready", "partial"].includes(entry.portState) ? "app::Ready" : null,
    entry.requiresReceive ? "app::RequiresRx" : null,
    entry.requiresTransmit ? "app::RequiresTx" : null,
    entry.portState === "browser port pending" ? "app::Pending" : null,
    entry.requiresAudio ? "app::RequiresAudio" : null,
    entry.requiresMap ? "app::RequiresMap" : null
  ].filter(Boolean).join("|") || "0";
  const source = `/* Generated from src/app_registry.json. File-scope Registrar mirrors mayhem-b200 registration semantics. */\n#include "../mayhem/app_registry.hpp"\nnamespace {\nstatic constexpr char kId[] = ${cppString(entry.id)};\nstatic constexpr char kName[] = ${cppString(entry.coreName || entry.name)};\nconst app::Registrar registrar{{kId, sizeof(kId)-1, kName, sizeof(kName)-1, app::Category::${entry.category}, ${flags}, ${Number(entry.preferredSampleRate || 0)}u, ${Number(entry.minimumSampleRate || 0)}u, ${Number(entry.requiredBandwidthHz || 0)}u}};\n}\n`;
  await writeFile(file, source);
  generatedAppSources.push(file);
}
// Keep a human-readable generated summary for audits; it is no longer compiled into the core.
const generatedCpp = [
  "/* v0.7 audit summary — native file-scope Registrars live in src/generated_apps/*.cpp. */",
  ...registry.map((entry, index) => `// ${String(index).padStart(2, "0")} ${entry.id} -> app::Category::${entry.category}`),
  ""
].join("\n");
await writeFile(path.join(root, "src", "generated_app_registry.inc"), generatedCpp);

await rm(dist, { recursive: true, force: true });
await mkdir(dist, { recursive: true });
await cp(web, dist, { recursive: true });
await mkdir(path.join(dist, "assets"), { recursive: true });
const packageJson = JSON.parse(await readFile(path.join(root, "package.json"), "utf8"));
for (const relative of ["index.html", "service-worker.js"]) {
  const target = path.join(dist, relative);
  const text = await readFile(target, "utf8");
  await writeFile(target, text.replaceAll("__APP_VERSION__", packageJson.version));
}

const wasmOutput = path.join(dist, "assets", "dsp_core.wasm");
const compile = spawnSync("clang", [
  "--target=wasm32", "-O3", "-nostdlib",
  "-Wl,--no-entry",
  "-Wl,--export=mayhem_rtl_convert_u8_iq",
  "-Wl,--export=mayhem_rtl_mean_power",
  "-Wl,--export=mayhem_rtl_dc_remove",
  "-Wl,--export=__heap_base",
  "-Wl,--export-memory",
  "-Wl,--initial-memory=2097152",
  "-Wl,--max-memory=67108864",
  "-Wl,--allow-undefined",
  "-o", wasmOutput,
  path.join(root, "src", "dsp", "dsp_core.c")
], { encoding: "utf8" });
if (compile.status !== 0) {
  process.stderr.write(compile.stdout || "");
  process.stderr.write(compile.stderr || "");
  throw new Error("Failed to compile the local WebAssembly sample kernel with clang.");
}

const coreOutput = path.join(dist, "assets", "mayhem_core.wasm");
const coreCompile = spawnSync("clang++", [
  "--target=wasm32", "-O3", "-nostdlib", "-fno-exceptions", "-fno-rtti",
  "-Wl,--no-entry",
  "-Wl,--export=mayhem_core_framebuffer_ptr",
  "-Wl,--export=mayhem_core_width",
  "-Wl,--export=mayhem_core_height",
  "-Wl,--export=mayhem_core_app_count",
  "-Wl,--export=mayhem_core_app_id_ptr",
  "-Wl,--export=mayhem_core_app_id_len",
  "-Wl,--export=mayhem_core_app_name_ptr",
  "-Wl,--export=mayhem_core_app_name_len",
  "-Wl,--export=mayhem_core_app_category",
  "-Wl,--export=mayhem_core_app_flags",
  "-Wl,--export=mayhem_core_registry_hash",
  "-Wl,--export=__wasm_call_ctors",
  "-Wl,--export=mayhem_core_set_source",
  "-Wl,--export=mayhem_core_set_receiver",
  "-Wl,--export=mayhem_core_set_radio_details",
  "-Wl,--export=mayhem_core_render",
  "-Wl,--export=mayhem_core_nav_depth",
  "-Wl,--export=mayhem_core_selected_index",
  "-Wl,--export=mayhem_core_last_activated_app",
  "-Wl,--export=mayhem_core_take_activation",
  "-Wl,--export=mayhem_core_input_key",
  "-Wl,--export=mayhem_core_input_encoder",
  "-Wl,--export=mayhem_core_input_pointer",
  "-Wl,--export-memory",
  "-Wl,--initial-memory=4194304",
  "-Wl,--max-memory=16777216",
  "-Wl,--allow-undefined",
  "-o", coreOutput,
  path.join(root, "src", "core_mayhem_bridge.cpp"),
  path.join(root, "src", "mayhem", "ui.cpp"),
  path.join(root, "src", "mayhem", "display.cpp"),
  path.join(root, "src", "mayhem", "painter.cpp"),
  path.join(root, "src", "mayhem", "app_registry.cpp"),
  path.join(root, "src", "mayhem", "navigation.cpp"),
  path.join(root, "src", "mayhem", "runtime.cpp"),
  ...generatedAppSources
], { encoding: "utf8" });
if (coreCompile.status !== 0) {
  process.stderr.write(coreCompile.stdout || "");
  process.stderr.write(coreCompile.stderr || "");
  throw new Error("Failed to compile the Mayhem WebAssembly core bridge with clang++.");
}

const distributableDocs = [
  "README.md", "CHANGELOG.md", "ARCHITECTURE.md", "TEST_PLAN.md", "TEST_RESULTS.md", "CONTRIBUTING.md",
  "LICENSE", "LICENSE.GPL-2.0-or-later", "LICENSE.Apache-2.0", "NOTICE.md",
  "SOURCE_ATTRIBUTION.md", "THIRD_PARTY_LICENSES.md", "PRIVACY.md", "SECURITY.md",
  "COMPATIBILITY.md", "PORTING_MATRIX.md", "UPSTREAM_RUNTIME_AUDIT.md", "UPSTREAM_COMMIT.txt", "WEBRTLSDR_COMMIT.txt"
];
await mkdir(path.join(dist, "documents"), { recursive: true });
for (const file of distributableDocs) await cp(path.join(root, file), path.join(dist, "documents", file));
await cp(path.join(root, "deployment"), path.join(dist, "documents", "deployment"), { recursive: true });
await cp(path.join(root, "tests", "results"), path.join(dist, "documents", "test-results"), { recursive: true });

await writeFile(path.join(dist, "version.json"), JSON.stringify({
  application: "MAYHEM RTL",
  version: packageJson.version,
  upstreamCommit: (await readFile(path.join(root, "UPSTREAM_COMMIT.txt"), "utf8")).trim(),
  webRtlSdrCommit: (await readFile(path.join(root, "WEBRTLSDR_COMMIT.txt"), "utf8")).trim(),
  builtAt: new Date().toISOString()
}, null, 2));

async function walk(directory, prefix = "") {
  const entries = await readdir(directory);
  const files = [];
  for (const entry of entries) {
    const absolute = path.join(directory, entry);
    const relative = path.posix.join(prefix, entry);
    const info = await stat(absolute);
    if (info.isDirectory()) files.push(...await walk(absolute, relative));
    else files.push(relative);
  }
  return files;
}

const assets = (await walk(dist))
  .filter((file) => file !== "service-worker.js")
  .map((file) => `./${file}`)
  .sort();
const serviceWorkerPath = path.join(dist, "service-worker.js");
const serviceWorker = (await readFile(serviceWorkerPath, "utf8")).replace("__ASSET_LIST__", JSON.stringify(assets, null, 2));
await writeFile(serviceWorkerPath, serviceWorker);

for (const file of (await walk(path.join(dist, "src"))).filter((name) => name.endsWith(".js"))) {
  const check = spawnSync(process.execPath, ["--check", path.join(dist, "src", file)], { encoding: "utf8" });
  if (check.status !== 0) throw new Error(`JavaScript syntax check failed for ${file}:\n${check.stderr}`);
}

console.log(`Built ${dist}`);
console.log(`Cached static assets: ${assets.length}`);
console.log(`WebAssembly kernel: ${wasmOutput}`);
console.log(`Mayhem core bridge: ${coreOutput}`);
